name_or_path: /home/luokaiwei/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct
tokenizer_name_or_path: /home/luokaiwei/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: bfloat16
auth_token: None
